profileimage: SURYA.jpg
about: Software Developer with n years of experience ...
skills:
- key: golang
  value: 70%
- key: javascript
  value: 50%
- key: HTML
  value: 60%
- key: jenkins
  value: 50%
- key: drone.io
  value: 50%
- key: git
  value: 75%
- key: Agile and Scrum
  value: 75%
experience:
- date: 2020 - Present
  company: Company 1
  designation: Project Lead
  description: Euismod massa scelerisque suspendisse fermentum habitant vitae ullamcorper magna quam iaculis, tristique sapien taciti mollis interdum sagittis libero nunc inceptos tellus, hendrerit vel eleifend primis lectus quisque cubilia sed mauris. Lacinia porta vestibulum diam integer quisque eros pulvinar curae, curabitur feugiat arcu vivamus parturient aliquet laoreet at, eu etiam pretium molestie ultricies sollicitudin dui.
- date: 2016 - 2020
  company: Company 2
  designation: Senior Principal Development Specialist
  description: Euismod massa scelerisque suspendisse fermentum habitant vitae ullamcorper magna quam iaculis, tristique sapien taciti mollis interdum sagittis libero nunc inceptos tellus, hendrerit vel eleifend primis lectus quisque cubilia sed mauris. Lacinia porta vestibulum diam integer quisque eros pulvinar curae, curabitur feugiat arcu vivamus parturient aliquet laoreet at, eu etiam pretium molestie ultricies sollicitudin dui.
- date: 2013 - 2016
  company: Company 3
  designation: Senior Software Engineer
  description: Euismod massa scelerisque suspendisse fermentum habitant vitae ullamcorper magna quam iaculis, tristique sapien taciti mollis interdum sagittis libero nunc inceptos tellus, hendrerit vel eleifend primis lectus quisque cubilia sed mauris. Lacinia porta vestibulum diam integer quisque eros pulvinar curae, curabitur feugiat arcu vivamus parturient aliquet laoreet at, eu etiam pretium molestie ultricies sollicitudin dui.
basicinfo:
  name: Your Name
  details:
  - key: Email
    value: youremail@domain.com
  - key: Phone
    value: (+00) 123456789
  - key: Address
    value: City, State ZIP
socialnetworks:
- key: github
  value: https://github.com
- key: linkedin
  value: https://linkedin.com
- key: instagram
  value: https://instagram.com
- key: medium
  value: https://medium.com
education:
- date: 2008 - 2012
  institutionname: Your University Name
  speciality: Bachelor of Information Technology
  degree: Bachelor's Degree
  description: Habitasse venenatis commodo tempor eleifend arcu sociis sollicitudin ante pulvinar ad, est porta cras erat ullamcorper volutpat metus duis platea convallis, tortor primis ac quisque etiam luctus nisl nullam fames. Ligula purus suscipit tempus nascetur curabitur donec nam ullamcorper, laoreet nullam mauris dui aptent facilisis neque elementum ac, risus semper felis parturient fringilla rhoncus eleifend.
